name: Build

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: git
        run: |
          git clone --recursive https://github.com/DBCTRADO/TVTest.git

      - name: msbuild
        run: |
          msbuild TVTest/src/LibISDB/Projects/LibISDB.sln /t:build /p:Configuration=Release

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LibISDB
          path: TVTest/src/LibISDB/Projects/x64