name: Build

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: git
        run: |
          git clone --recursive https://github.com/DBCTRADO/TVTest.git
          cd TVTest
          msbuild src/LibISDB/Projects/LibISDB.sln /t:build /p:Configuration=Release